---
port:
  name: /dev/ttyUSB0
  baudRate: 9600
  dataBits: 8
  parity: None
  stopBits: 1
database:
  host: 127.0.0.1:3306
  dbname: yourDatabaseName
  username: yourDatabaseUsername
  password: yourDatabasePassword
